version: "3.8"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
  web:
    build: .
    command: . env/bin/activate && gunicorn --bind 0.0.0.0:8000 config.wsgi
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db